services:
  - type: web
    name: eventease-backend
    env: node
    plan: free
    buildCommand: npm install --prefix eventease/backend
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        scope: build,runtime
        value: mongodb://localhost:27017/eventease
      - key: JWT_SECRET
        scope: build,runtime
        value: your_jwt_secret_key_change_in_production
      - key: PORT
        scope: build,runtime
        value: 10000
      - key: NODE_ENV
        scope: build,runtime
        value: production

  - type: web
    name: eventease-frontend
    env: node
    plan: free
    buildCommand: cd eventease/frontend/eventease && npm install && npm run build
    startCommand: cd eventease/frontend/eventease && node server.js
    envVars:
      - key: VITE_API_URL
        scope: build
        value: https://eventease-backend-loau.onrender.com/api
      - key: PORT
        scope: runtime
        value: 3000
